# Generated by Django 3.2.3 on 2025-02-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posApp.products'),
            preserve_default=False,
        ),
    ]
