# Generated by Django 3.2.3 on 2025-02-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_auto_20250215_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitems',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='salesitems',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posApp.sales'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
