# Generated by Django 3.2.3 on 2025-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_auto_20250215_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitems',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='salesitems',
            old_name='sale',
            new_name='sale_id',
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
